language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

install:
  - npm i
  - npm install element-ui@2
  - npm install vue@2

stages:
  - lint
  - name: gh_pages
    if: branch = dev

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: gh_pages
      script: npm run build
      after_script:
        - git clone -b gh-pages "https://${GH_TOKEN}@${GH_REF}" gh-pages
        - rm -r gh-pages/*
        - cp -r example-dist/. gh-pages
        - cd ./gh-pages
        - git config user.name "leezng"
        - git config user.email "im.leezng@gmail.com"
        - git add .
        - git commit -m "update gh-pages"
        - git push --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages

env:
  global:
    - GH_REF: github.com/leezng/element-patch.git
